version: '1.0'
stages:
  - prepare
  - verify
  - build
  - integration test
steps:
  main_clone:
    title: Cloning main repository...
    stage: prepare
    type: git-clone
    repo: 'kaleesztech/codefresh-testing'
    revision: main
  spinup_svc:
    title: spinning up all necessary svc
    stage: verify
    image: pwbdod/docker-compose-aws-tf
    working_directory: ${{main_clone}}
    shell: sh
    commands:
      - |-
        sleep 15s
        if [[ -f docker-compose.yml ]]; then
          docker-compose up -d
        else
          echo -e "file is not present"
        fi
